### ISSUE TITLE
hardware.py has no unit test coverage.

### ISSUE THREAD

**Issue by theTechnoWeenie** [hackernight/portal#15]

**Comment by icbat** [comment]
We should look in to unittest instead of nose. A lot of flask methods (jsonify in particular) are not compatible with nose, but it looks like the flask folks use unitest

http://flask.pocoo.org/docs/0.10/testing/

**Comment by theTechnoWeenie** [comment]
I'm in for whatever regarding unit tests, so sure. Are you @icbat already looking into this, or should I do it as part of this task?

**Comment by icbat** [comment]
I have not looked in to this yet, no. If I have time I'll probably convert the existing tests to unittest.

Actually, when we did Spyglass, we used unittest.

**Comment by theTechnoWeenie** [comment]
I closed this as a dup since apparently I'm bad at git hub issues.
